/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 
 */
public class FinishCheckLine extends javax.swing.JFrame {
    private Reservations reser;
    private Main princ;
    /**
     * Creates new form FinishCheckLine
     */
    public FinishCheckLine(Reservations reserva, Main prin, int pos) {
        initComponents();
        reser = reserva;
        princ = prin;
        this.setExtendedState(MAXIMIZED_BOTH);
        //this.setUndecorated(true);
        
        //[null][Single][168763][2227964][2][1][June][July][Luis][Santillanes][Delicias][Mexico][ID][6391128877][luis@gmail.com][CCNumber][CCHoster][02][2021][362][null]
        String pin = "";
        pinHabitacion(5, pin, princ.getsArreglo(), pos);
        System.out.println("PIN de hab = " + princ.getsArreglo()[pos][21]);
        lblPIN.setText(princ.getsArreglo()[pos][21]);
        
                        // 1-50    51-100    101-120   121
        int numHab = 0;
        switch(princ.getsArreglo()[pos][1]){
            case "Single":
                numHab = (int)(Math.random()*50+1);
                System.out.println("Single");
                break;
            case "Double":
                numHab = (int)(Math.random()*50+51);
                System.out.println("Double");
                break;
            case "Suite":
                numHab = (int)(Math.random()*20+101);
                System.out.println("Suite");
                break;
            case "Presidential Suite":
                numHab = 121;
                break;
        }
        princ.getsArreglo()[pos][20] = String.valueOf(numHab);
        lblRoom.setText(princ.getsArreglo()[pos][20]);
        System.out.println("\nArreglo final");
        for (int i = 0; i < princ.getsArreglo().length; i++) {
            for (int j = 0; j < princ.getsArreglo()[i].length; j++) {
                System.out.print("["+princ.getsArreglo()[i][j]+"]");
            }
            System.out.println("");
        }
    }
    
    public static void pinHabitacion(int num, String us, String[][] arreglo, int pos){
        System.out.println("us = " + us);
        us += ((int)(Math.random()*10));
        if(num>0){
            pinHabitacion(num-1, us, arreglo, pos);
        }else
            arreglo[pos][21] = us;
    }
    

    private FinishCheckLine() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblRoom = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPIN = new javax.swing.JLabel();
        btnFinish = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Check-In Complete!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 146, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Your room is: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, 362, -1, -1));

        lblRoom.setBackground(new java.awt.Color(184, 162, 189));
        lblRoom.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblRoom.setForeground(new java.awt.Color(255, 255, 255));
        lblRoom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRoom.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(914, 424, 120, 44));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("The PIN of your room is: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 570, -1, -1));

        lblPIN.setBackground(new java.awt.Color(184, 162, 189));
        lblPIN.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblPIN.setForeground(new java.awt.Color(255, 255, 255));
        lblPIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPIN.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(914, 632, 120, 44));

        btnFinish.setBackground(new java.awt.Color(184, 162, 189));
        btnFinish.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btnFinish.setForeground(new java.awt.Color(255, 255, 255));
        btnFinish.setText("Finish Check-In");
        btnFinish.setToolTipText("");
        btnFinish.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(871, 898, 200, -1));

        jPanel1.setBackground(new java.awt.Color(184, 162, 189));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        // TODO add your handling code here:
        new Inicio(reser, princ).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFinishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinishCheckLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinishCheckLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinishCheckLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinishCheckLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinishCheckLine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPIN;
    private javax.swing.JLabel lblRoom;
    // End of variables declaration//GEN-END:variables
}
