
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 
 */
public class Reservaciones extends javax.swing.JFrame {
    private Reservations reser;
    private Main princ;
    /**
     * Creates new form Reservaciones
     */
    public Reservaciones(Reservations res, Main prin, boolean verificar) {
        initComponents();
        reser = res;
        princ = prin;
        this.setExtendedState(MAXIMIZED_BOTH);
        //this.setUndecorated(true);
        
        if (verificar) {
            cbxRoom.setSelectedItem(res.getTipoHab());
            cboxAday.setSelectedItem(res.getDiaLlegada());
            cboxAmont.setSelectedItem(res.getMesLlegada());
            cboxAyear.setSelectedItem(res.getAñoLlegada());
            cboxDday.setSelectedItem(res.getDiaSalida());
            cboxDmonth.setSelectedItem(res.getMesSalida());
            cboxDyear.setSelectedItem(res.getAñoSalida());
            spnrAdults.setValue(res.getAdultos());
            spnrChildren.setValue(res.getNiños());
        }
    }

    private Reservaciones() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbxRoom = new javax.swing.JComboBox<>();
        spnrAdults = new javax.swing.JSpinner();
        spnrChildren = new javax.swing.JSpinner();
        cboxAday = new javax.swing.JComboBox<>();
        cboxAmont = new javax.swing.JComboBox<>();
        cboxAyear = new javax.swing.JComboBox<>();
        cboxDday = new javax.swing.JComboBox<>();
        cboxDmonth = new javax.swing.JComboBox<>();
        cboxDyear = new javax.swing.JComboBox<>();
        btnNext = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RESERVATIONS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 72, -1, -1));

        cbxRoom.setBackground(new java.awt.Color(184, 162, 189));
        cbxRoom.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        cbxRoom.setForeground(new java.awt.Color(255, 255, 255));
        cbxRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Single", "Double", "Suite", "Presidential Suite" }));
        cbxRoom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(cbxRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 325, 210, -1));

        spnrAdults.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        spnrAdults.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));
        spnrAdults.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(spnrAdults, new org.netbeans.lib.awtextra.AbsoluteConstraints(1028, 325, 70, -1));

        spnrChildren.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        spnrChildren.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));
        spnrChildren.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(spnrChildren, new org.netbeans.lib.awtextra.AbsoluteConstraints(1625, 325, 70, -1));

        cboxAday.setBackground(new java.awt.Color(184, 162, 189));
        cboxAday.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        cboxAday.setForeground(new java.awt.Color(255, 255, 255));
        cboxAday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cboxAday.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(cboxAday, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 679, -1, -1));

        cboxAmont.setBackground(new java.awt.Color(184, 162, 189));
        cboxAmont.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        cboxAmont.setForeground(new java.awt.Color(255, 255, 255));
        cboxAmont.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cboxAmont.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(cboxAmont, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 679, -1, -1));

        cboxAyear.setBackground(new java.awt.Color(184, 162, 189));
        cboxAyear.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        cboxAyear.setForeground(new java.awt.Color(255, 255, 255));
        cboxAyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "2020", "2021" }));
        cboxAyear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(cboxAyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 679, -1, -1));

        cboxDday.setBackground(new java.awt.Color(184, 162, 189));
        cboxDday.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        cboxDday.setForeground(new java.awt.Color(255, 255, 255));
        cboxDday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cboxDday.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(cboxDday, new org.netbeans.lib.awtextra.AbsoluteConstraints(1196, 679, -1, -1));

        cboxDmonth.setBackground(new java.awt.Color(184, 162, 189));
        cboxDmonth.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        cboxDmonth.setForeground(new java.awt.Color(255, 255, 255));
        cboxDmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cboxDmonth.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(cboxDmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(1269, 679, -1, -1));

        cboxDyear.setBackground(new java.awt.Color(184, 162, 189));
        cboxDyear.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        cboxDyear.setForeground(new java.awt.Color(255, 255, 255));
        cboxDyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "2020", "2021" }));
        cboxDyear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(cboxDyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1431, 679, -1, -1));

        btnNext.setBackground(new java.awt.Color(184, 162, 189));
        btnNext.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Next");
        btnNext.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(914, 904, 84, -1));

        jPanel1.setBackground(new java.awt.Color(184, 162, 189));

        btnExit.setBackground(new java.awt.Color(184, 162, 189));
        btnExit.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Adults:");

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Departure:");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Children:");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Room Type:");

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Arrival:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel10)
                .addGap(522, 522, 522)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 454, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(305, 305, 305))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(471, 471, 471))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addGap(246, 246, 246)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(0, 412, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        new EnglishMain(reser, princ).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        reser.setTipoHab(cbxRoom.getSelectedItem().toString());
        reser.setAdultos(Integer.parseInt(spnrAdults.getValue().toString()));
        reser.setNiños(Integer.parseInt(spnrChildren.getValue().toString()));
        reser.setDiaLlegada(cboxAday.getSelectedItem().toString());
        //reser.setMesLlegada(cboxAmont.getSelectedItem().toString());
        reser.setAñoLlegada(cboxAyear.getSelectedItem().toString());
        reser.setDiaSalida(cboxDday.getSelectedItem().toString());
        //reser.setMesSalida(cboxDmonth.getSelectedItem().toString());
        reser.setAñoSalida(cboxDyear.getSelectedItem().toString());
        
        //COMPROBAR FECHA
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        Date llegada = null, salida = null;
        String ad = cboxAday.getSelectedItem().toString();
        String am = cboxAmont.getSelectedItem().toString();
        String ay = cboxAyear.getSelectedItem().toString();
        String dd = cboxDday.getSelectedItem().toString();
        String dm = cboxDmonth.getSelectedItem().toString();
        String dy = cboxDyear.getSelectedItem().toString();
        //-, Janurary, Februrary, March, April, May, June, July, August, September, October, November, December
        switch (am){
            case "January":
                am = "01";
                break;
            case "February":
                am = "02";
                break;
            case "March":
                am = "03";
                break;
            case "April":
                am = "04";
                break;
            case "May":
                am = "05";
                break;
            case "June":
                am = "06";
                break;
            case "July":
                am = "07";
                break;
            case "August":
                am = "08";
                break;
            case "September":
                am = "09";
                break;
            case "October":
                am = "10";
                break;
            case "November":
                am = "11";
                break;
            case "December":
                am = "12";
                break;
        }
        reser.setMesLlegada(am);
        switch (dm){
            case "January":
                dm = "01";
                break;
            case "February":
                dm = "02";
                break;
            case "March":
                dm = "03";
                break;
            case "April":
                dm = "04";
                break;
            case "May":
                dm = "05";
                break;
            case "June":
                dm = "06";
                break;
            case "July":
                dm = "07";
                break;
            case "August":
                dm = "08";
                break;
            case "September":
                dm = "09";
                break;
            case "October":
                dm = "10";
                break;
            case "November":
                dm = "11";
                break;
            case "December":
                dm = "12";
                break;
        }
        reser.setMesSalida(dm);
        try {
            llegada = sdf.parse(ad+"-"+am+"-"+ay);
            salida = sdf.parse(dd+"-"+dm+"-"+dy);
        } catch (ParseException ex) {
            Logger.getLogger(Reservaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
            if (cbxRoom.getSelectedItem() == "-" || cboxAday.getSelectedItem() == "-" || cboxAmont.getSelectedItem() == "-" || cboxAyear.getSelectedItem() == "-"   ||
                   cboxDday.getSelectedItem() == "-" || cboxDmonth.getSelectedItem() == "-" || cboxDyear.getSelectedItem() == "-"  ) {
                JOptionPane.showMessageDialog(this, "Enter all fields to continue.");
            }else if(llegada.compareTo(salida) != -1){
                JOptionPane.showMessageDialog(null, "Fecha inválida.");
            }else{
                try {
                    new Information(reser, princ, false).setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(Reservaciones.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.dispose();
            }
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox<String> cboxAday;
    private javax.swing.JComboBox<String> cboxAmont;
    private javax.swing.JComboBox<String> cboxAyear;
    private javax.swing.JComboBox<String> cboxDday;
    private javax.swing.JComboBox<String> cboxDmonth;
    private javax.swing.JComboBox<String> cboxDyear;
    private javax.swing.JComboBox<String> cbxRoom;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JSpinner spnrAdults;
    private javax.swing.JSpinner spnrChildren;
    // End of variables declaration//GEN-END:variables
}
