
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carla
 */
public class Tarifas extends javax.swing.JFrame {
    private Reservations reser;
    private Main princ;
    /**
     * Creates new form Tarifas
     */
    public Tarifas(Reservations res, Main prin) {
        initComponents();
        reser = res;
        princ = prin;
    }

    private Tarifas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spnrAdults = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        cboxDay = new javax.swing.JComboBox<>();
        cboxMonth = new javax.swing.JComboBox<>();
        cboxYear = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaTariffs = new javax.swing.JTextArea();
        cboxDay2 = new javax.swing.JComboBox<>();
        cboxMonth2 = new javax.swing.JComboBox<>();
        cboxYear2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnCost = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        spnrChildren = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        cboxRoom = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tariffs");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 72, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Room Tipe:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 238, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Adults:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1095, 238, -1, -1));

        spnrAdults.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        spnrAdults.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));
        spnrAdults.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(spnrAdults, new org.netbeans.lib.awtextra.AbsoluteConstraints(1224, 242, 70, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Arrival:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 451, -1, -1));

        cboxDay.setBackground(new java.awt.Color(184, 162, 189));
        cboxDay.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        cboxDay.setForeground(new java.awt.Color(255, 255, 255));
        cboxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cboxDay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(cboxDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 508, -1, -1));

        cboxMonth.setBackground(new java.awt.Color(184, 162, 189));
        cboxMonth.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        cboxMonth.setForeground(new java.awt.Color(255, 255, 255));
        cboxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cboxMonth.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(cboxMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 508, -1, -1));

        cboxYear.setBackground(new java.awt.Color(184, 162, 189));
        cboxYear.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        cboxYear.setForeground(new java.awt.Color(255, 255, 255));
        cboxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "", "2020", "2021" }));
        cboxYear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(cboxYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 508, -1, -1));

        txaTariffs.setColumns(20);
        txaTariffs.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        txaTariffs.setRows(5);
        txaTariffs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        txaTariffs.setEnabled(false);
        jScrollPane1.setViewportView(txaTariffs);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 595, 761, 344));

        cboxDay2.setBackground(new java.awt.Color(184, 162, 189));
        cboxDay2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        cboxDay2.setForeground(new java.awt.Color(255, 255, 255));
        cboxDay2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cboxDay2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(cboxDay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1157, 508, -1, -1));

        cboxMonth2.setBackground(new java.awt.Color(184, 162, 189));
        cboxMonth2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        cboxMonth2.setForeground(new java.awt.Color(255, 255, 255));
        cboxMonth2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cboxMonth2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(cboxMonth2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 508, -1, -1));

        cboxYear2.setBackground(new java.awt.Color(184, 162, 189));
        cboxYear2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        cboxYear2.setForeground(new java.awt.Color(255, 255, 255));
        cboxYear2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "", "2020", "2021" }));
        cboxYear2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(cboxYear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1392, 508, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Departure:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 446, -1, -1));

        btnCalculate.setBackground(new java.awt.Color(184, 162, 189));
        btnCalculate.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculate.setText("Calculate");
        btnCalculate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 986, 117, -1));

        btnExit.setBackground(new java.awt.Color(184, 162, 189));
        btnExit.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1834, 0, 86, -1));

        btnCost.setBackground(new java.awt.Color(184, 162, 189));
        btnCost.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnCost.setForeground(new java.awt.Color(255, 255, 255));
        btnCost.setText("?");
        btnCost.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCostActionPerformed(evt);
            }
        });
        getContentPane().add(btnCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 255, 33, -1));

        jPanel1.setBackground(new java.awt.Color(184, 162, 189));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spnrChildren.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        spnrChildren.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));
        spnrChildren.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        jPanel1.add(spnrChildren, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 240, 70, 44));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Children:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 240, -1, -1));

        cboxRoom.setBackground(new java.awt.Color(184, 162, 189));
        cboxRoom.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        cboxRoom.setForeground(new java.awt.Color(255, 255, 255));
        cboxRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Single", "Double", "Suite", "Presidential Suite" }));
        cboxRoom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        jPanel1.add(cboxRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCostActionPerformed
        // TODO add your handling code here:
        new Cost(reser, princ).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCostActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        
        new EnglishMain(reser, princ).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        //COMPROBAR FECHA
        
        txaTariffs.setText("");
        
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            Date llegada = null, salida = null;
            String ad = cboxDay.getSelectedItem().toString();
            String am = cboxMonth.getSelectedItem().toString();
            String ay = cboxYear.getSelectedItem().toString();
            String dd = cboxDay2.getSelectedItem().toString();
            String dm = cboxMonth2.getSelectedItem().toString();
            String dy = cboxYear2.getSelectedItem().toString();
            //-, Janurary, Februrary, March, April, May, June, July, August, September, October, November, December
            switch (am){
                case "January":
                    am = "01";
                    break;
                case "February":
                    am = "02";
                    break;
                case "March":
                    am = "03";
                    break;
                case "April":
                    am = "04";
                    break;
                case "May":
                    am = "05";
                    break;
                case "June":
                    am = "06";
                    break;
                case "July":
                    am = "07";
                    break;
                case "August":
                    am = "08";
                    break;
                case "September":
                    am = "09";
                    break;
                case "October":
                    am = "10";
                    break;
                case "November":
                    am = "11";
                    break;
                case "December":
                    am = "12";
                    break;
            }
            switch (dm){
                case "January":
                    dm = "01";
                    break;
                case "February":
                    dm = "02";
                    break;
                case "March":
                    dm = "03";
                    break;
                case "April":
                    dm = "04";
                    break;
                case "May":
                    dm = "05";
                    break;
                case "June":
                    dm = "06";
                    break;
                case "July":
                    dm = "07";
                    break;
                case "August":
                    dm = "08";
                    break;
                case "September":
                    dm = "09";
                    break;
                case "October":
                    dm = "10";
                    break;
                case "November":
                    dm = "11";
                    break;
                case "December":
                    dm = "12";
                    break;
            }
            System.out.println("ad = " + ad);
            System.out.println("am = " + am);
            System.out.println("ay = " + ay);
            System.out.println("dd = " + dd);
            System.out.println("dm = " + dm);
            System.out.println("dy = " + dy);
            try {
                llegada = sdf.parse(ad+"-"+am+"-"+ay);
                salida = sdf.parse(dd+"-"+dm+"-"+dy);
            } catch (ParseException ex) {
                Logger.getLogger(Reservaciones.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        
        if (cboxDay.getSelectedItem() == "-" || cboxDay2.getSelectedItem() == "-" || cboxMonth.getSelectedItem() == "-" || cboxMonth2.getSelectedItem() == "-"
                || cboxRoom.getSelectedItem() == "-" || cboxYear.getSelectedItem() == "-" || cboxYear2.getSelectedItem() == "-") {
            JOptionPane.showMessageDialog(this, "Enter all fields to continue.");
        }else if(llegada.compareTo(salida) != -1){
                JOptionPane.showMessageDialog(null, "Fecha inválida.");
        }else{
            
            int totAdu = 0, totNi = 0, TOT = 0;
        switch(cboxRoom.getSelectedItem().toString()){
            case "Single":
                totAdu = (((int)(spnrAdults.getValue()))*1000);
                totNi = (((int)(spnrChildren.getValue()))*600);
                break;
            case "Double":
                totAdu = (((int)(spnrAdults.getValue()))*1200);
                totNi = (((int)(spnrChildren.getValue()))*800);
                break;
            case "Suite":
                totAdu = (((int)(spnrAdults.getValue()))*1500);
                totNi = (((int)(spnrChildren.getValue()))*1100);
                break;
            case "Presidential Suite":
                totAdu = (((int)(spnrAdults.getValue()))*3800);
                totNi = (((int)(spnrChildren.getValue()))*2800);
                break;
        }
        
        
        try {
            llegada = sdf.parse(ad+"-"+am+"-"+ay);
            salida = sdf.parse(dd+"-"+dm+"-"+dy);
        } catch (ParseException ex) {
            Logger.getLogger(Reservaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        long diasLleg = llegada.getTime();
        long diasSal = salida.getTime();
        long diasTotal = (diasSal - diasLleg)/86400000;
        
        TOT = (totAdu+totNi)*((int)(diasTotal));
        
        txaTariffs.append(
                "Room type: "+(cboxRoom.getSelectedItem())+
                "\nAdults: "+(spnrAdults.getValue())+
                "\nChildren: "+(spnrChildren.getValue())+
                "\nArrival date: "+(cboxDay.getSelectedItem())+"/"+(cboxMonth.getSelectedItem())+"/"+(cboxYear.getSelectedItem())+
                "\nDeparture date: "+(cboxDay2.getSelectedItem())+"/"+(cboxMonth2.getSelectedItem())+"/"+(cboxYear2.getSelectedItem())+
                "\nTotal nights: "+diasTotal+
                "\nTotal: $"+TOT+" pesos."
        );
            
            
            
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tarifas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tarifas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tarifas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarifas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tarifas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnCost;
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox<String> cboxDay;
    private javax.swing.JComboBox<String> cboxDay2;
    private javax.swing.JComboBox<String> cboxMonth;
    private javax.swing.JComboBox<String> cboxMonth2;
    private javax.swing.JComboBox<String> cboxRoom;
    private javax.swing.JComboBox<String> cboxYear;
    private javax.swing.JComboBox<String> cboxYear2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnrAdults;
    private javax.swing.JSpinner spnrChildren;
    private javax.swing.JTextArea txaTariffs;
    // End of variables declaration//GEN-END:variables
}
